server:
  port: 8080

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
    cluster:
      nodes: localhost:6379